"""created new columns

Revision ID: 05697d341500
Revises: 4dad6d33ac4b
Create Date: 2019-07-05 12:45:21.193737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05697d341500'
down_revision = '4dad6d33ac4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('dislikes', sa.Integer(), nullable=True))
    op.add_column('blogs', sa.Column('likes', sa.Integer(), nullable=True))
    op.drop_column('blogs', 'upvotes')
    op.drop_column('blogs', 'downvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('blogs', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'likes')
    op.drop_column('blogs', 'dislikes')
    # ### end Alembic commands ###
